
include:
  - project: 'devops/gitlabci-templates'
    ref: master
    file: 'jobs-templates/include-all.stable.gitlab-ci.yml'

default:
  image: ${TOOLBOX_IMAGE}

stages:
 - build

before_script:
  - |
    GO_MOD_PROJECT=$(git remote -v|awk 'NR==1{print $2}'|awk -F '//' '{print $2}'|sed "s#\.git##g"|awk -F '@' '{print $2}')
    mkdir -p /go/src/${GO_MOD_PROJECT}
    cp -r $CI_PROJECT_DIR/ /go/src/${GO_MOD_PROJECT}
    printenv

build:
  stage: build
  timeout: 2 hours
  image: harbor.treesir.pub:2443/library/base-image:golang-1.20.2
  tags:
    - manage
  script:
    - |
      apt update && apt install -y git >/dev/null 2>&1
      GO_MOD_PROJECT=$(git remote -v|awk 'NR==1{print $2}'|awk -F '//' '{print $2}'|sed "s#\.git##g"|awk -F '@' '{print $2}')
      cd /go/src/${GO_MOD_PROJECT}/
      ls

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH