
include:
  - project: 'devops/gitlabci-templates'
    ref: master
    file: 'jobs-templates/include-all.stable.gitlab-ci.yml'

default:
  image: ${TOOLBOX_IMAGE}
  timeout: 2 hours

variables:
  ARCH: amd64
  OS_TYPE: linux
  AUTH: "${NEXUS_USER}:${NEXUS_PASSWORD}"
  REPO_URL: "https://nexus.iquantex.com/repository/static-file/devops-tools/"
  GO111MODULE: "on"
  GOPROXY: "https://goproxy.cn"

.test:
  stage: test
  tags:
    - manage
  retry:
    max: 2
  rules:
    - when: always
    
stages:
 - build
 - test
 - upload

before_script:
  - |
    GIT_SERVER=$(echo $CI_SERVER_URL|awk -F '//' '{print $2}')
    mkdir -p /go/src/${GIT_SERVER}/$CI_PROJECT_ROOT_NAMESPACE
    cp -r $CI_PROJECT_DIR/ /go/src/${GIT_SERVER}/$CI_PROJECT_ROOT_NAMESPACE/

build:
  stage: build
  image: harbor.treesir.pub:2443/library/base-image:golang-1.20.2
  tags:
    - manage
  script:
    - |
      apt update >/dev/null 2>&1 && apt install -y git >/dev/null 2>&1
      GO_MOD_PROJECT=$(git remote -v|awk 'NR==1{print $2}'|awk -F '//' '{print $2}'|sed "s#\.git##g"|awk -F '@' '{print $2}')
      cd /go/src/${GO_MOD_PROJECT}/
      scripts/build.sh ${ARCH} ${OS_TYPE} ${CI_PROJECT_DIR}/bin
  cache:
    key: plugin
    paths:
      - bin/
    policy: push

.test_build: &test_build
  extends: 
    - .test
  script:
    - set -- $CI_JOB_NAME
    - |
      cd test/$1
      bash run.sh
  cache:
    key: plugin
    paths:
      - bin/
    policy: pull

baseCharter test: *test_build

upload:
  stage: upload
  image: harbor.treesir.pub:2443/library/base-image:golang-1.20.2
  tags:
    - manage
  cache:
    key: plugin
    paths:
      - bin/
    policy: pull
  artifacts:
    paths:
      - bin/
    expire_in: 1 week
  script:
    - |
      # upload artifact
      for plugin in `ls ./bin/*`;do
         echo "Pushing $plugin to repo $REPO_URL..."
         curl -u "${AUTH}" "${REPO_URL}" --upload-file "$plugin" -v
         if [[ $(echo $?) -ne 0 ]];then
           echo "Failed to upload $plugin to repo $REPO_URL"
           exit 1 && break
         fi
         echo "Done"
      done
  when: manual

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH